name: Error Check

on: push

jobs:
  error_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all project files
        run: ls -R

      - name: Validate HTML files
        run: |
          sudo npm install -g htmlhint
          htmlhint .
